Add enrichment metadata
Dynatrace/OneAgent-SDK-for-Go pull request #3
Opened 2022-05-31 13:20 UTC by PeterFeicht

This adds two different implementations for getting log enrichment metadata from OneAgent. One requires the Go code module be injected (but doesn't require use of cgo); the other does not require the Go code module be injected, but requires use of cgo on Linux.

1. I did not add an example for the new functionality, because I don't think it would add any value. Let me know if you want me to add one anyway.
2. We need to improve the documentation with regards to required OneAgent versions. As soon as we have more than one feature, "the SDK" doesn't require a particular OneAgent version, but "feature A" and "feature B" may require different ones.
3. Should all functions be documented in the README as well as the source code? Since documentation will be generated automatically [on pkg.go.dev](https://pkg.go.dev/github.com/Dynatrace/OneAgent-SDK-for-Go) for the module, I suggest we put as much documentation as possible in source code instead of the readme (and link to pkg.go.dev from the latter).

ONE-75361

2022-06-01 08:38 UTC, michael-obermueller commented
Ad 1:
To be consistent I would add an example. Also consider to provide a minimal docker file which sets up gcc to be able to build an app on Linux which requires cgo.

Ad 2:
Yes, the `native/enrichment` API would also work with older OneAgent versions and is independent of the Go SDK API instrumented by the Go agent. I propose to add the required OneAgent version to the `function/package` documentation.

Ad 3:
That's something we should discuss with @z1c0, because this would not match with the documentation guidelines of other agent SDKs. However, as you said [pkg.go.dev](https://pkg.go.dev/github.com/Dynatrace/OneAgent-SDK-for-Go) generates nice documentation of [the API](https://pkg.go.dev/github.com/Dynatrace/OneAgent-SDK-for-Go@v1.0.0/sdk/trace) automatically which is what Go developers usually expect.

2022-06-01 08:41 UTC, michael-obermueller requested changes
I'm ok with your changes, but as described in the last comment we need a solution to document OneAgent version requirements of `native/enrichment` and a sample should be provided.

2022-06-01 08:47 UTC, PeterFeicht commented
1. Consistent with the one thing that already exists, I don't see the value in that. We already link to documentation that shows how the returned values can be used, so a minimal example would probably consist of printing a map...
2. My thoughts exactly.
3. We should definitely stick with what's common for Go libraries, not try and conform to some arbitrary guidelines just for the sake of being consistent with completely unrelated SDKs.

2022-06-01 13:25 UTC, michael-obermueller commented
@z1c0 to add this functionality to the Go SDK was discussed with our PM and LPE. This mechanism is only necessary for Golang, because the approach of the process agent to provide the magic file works out of the box for other technologies, please see ONE-75361 for more details.

I was not aware of https://github.com/Dynatrace/OneAgent-SDK, or forgot about it... should we add a specification despite the fact that this is only necessary for Golang?

2022-06-01 13:35 UTC, PeterFeicht commented
> However, I would still appreciate a brief mention of the feature in the README for sake of consistency with other OneAgent SDKs.

Sure, we'll add that in a separate PR when we overhaul the documentation.

2022-06-02 07:02 UTC, YuriiBarninets approved these changes

2022-06-02 11:16 UTC, michael-obermueller approved these changes
as discussed documentation changes will be added in another PR

2022-06-02 11:18 UTC, merged